language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'import OnlinePackage, Pkg; Pkg.add("Coverage"); import Coverage.Codecov; OnlinePackage |> pathof |> dirname |> Codecov.process_folder |> Codecov.submit'
  - julia -e 'import OnlinePackage, Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); joinpath(OnlinePackage |> pathof |> dirname |> dirname, "docs", "make.jl") |> include'
